**What is NUmPy?**

NumPy stands for "Numerical Python". It is a fundamental python pacakge used to perform Numerical computation. Numpy provides multi-dimensional array object called "ndarry" and various function to perform operations on the array.

**Why NumPy**



*   NumPy is 50x faster than the python lists.
*   It occupies less space.
*   We can perform various operations on numpy arrays.
*   It is also used in Machine Learning and Data Science.



**How to install NumPy?**

we can install NumPy from the command prompt by using "pip".



In [ ]:
pip install numpy

**How to import Python?**

We can import python with the help of "import" keyword.

In [ ]:
import numpy as np

# Creating Arrays

We can Create arrays in different ways:

1. np.array()
2. np.arange()
3. np.zeros()
4. np.ones()
5. np.empty()
6. np.eye() or np.identity()
7. np.inspace()
8. np.random.rand()
9. np.random.randn()
10. np,random.randint()

In [ ]:
#1. np.array() - we can create arrays with lists and tuples.

#lists
array_1d = np.array([1,2,3,4])
array_2d = np.array([[1,2,3,4],[1,2,3,4]])
array_3d = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])

print(f"{array_1d}\n\n{array_2d}\n\n{array_3d}")


#tuples
array_11d = np.array((1,2,3,4))
array_22d = np.array(((1,2,3,4),(1,2,3,4)))

print(f"{array_11d}\n\n{array_22d}")

[1 2 3 4]

[[1 2 3 4]
 [1 2 3 4]]

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
[1 2 3 4]

[[1 2 3 4]
 [1 2 3 4]]


In [ ]:
"""
2. np.arange() - used to create arrays with evenly spaced values. It creates a sequence and only one-dimensional array.

syntax:

        np.arange(start,stop,step)

        start - starts from specified value(inclusive) - default 0
        stop  - stops at sepcified value(exclusive)
        step  - to determine interval between values - default 1
"""
array_1 = np.arange(5)   # 0 - 4
array_2 = np.arange(2,10) # 2 - 9
array_3 = np.arange(1,10,2)  # 1 - 9 with step 2
array_4 = np.arange(10,0,-2)  # 10 - 1 with step -2

print(f"{array_1}\n{array_2}\n{array_3}\n{array_4}")

[0 1 2 3 4]
[2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[10  8  6  4  2]


In [ ]:
#3. np.zeros() - used to create arrays with zeros

#1d : 5 represnts length of the one-dimension
array_1d = np.zeros(5)
print(array_1d,"\n")

#2d : 2 rows and 3 columns
array_2d = np.zeros((2,3))
print(array_2d,"\n")

#3d : 2 blocks, 2 rows and 3 columns
array_3d = np.zeros((2,2,3))
print(array_3d)

[0. 0. 0. 0. 0.] 

[[0. 0. 0.]
 [0. 0. 0.]] 

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
#4. np.ones() - used to create arrays filled with one. In default the data type is float. we can change it using "dtype" parameter.

#1d : 5 reprsents length of one-dimensional array
array_1d = np.ones(5)
print(array_1d,"\n")

#2d : 2 rows 3 columns
array_2d = np.ones((2,3))
print(array_2d,"\n")

#3d : 2 blocks,2 rows and 3 columns
array_3d = np.ones((2,2,3))
print(array_3d,"\n")

#data type float to int
array_type1 = np.ones((2,3),dtype="int")
print(array_type1,"\n")

array_type2 = np.ones(5,dtype="str")
print(array_type2)

[1. 1. 1. 1. 1.] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
[[1 1 1]
 [1 1 1]] 

['1' '1' '1' '1' '1']


In [ ]:
#5. np.empty() - creates a array with garabage values or previously used output.

#1d : 3 length of the array
array_1d = np.empty(3)
print(array_1d,"\n")

#2d : 2 rows and 3 columns
array_2d = np.empty((2,3))
print(array_2d,"\n")

#3d : 2 blocks,2 rows and 3 columns
array_3d = np.empty((2,2,3))
print(array_3d)

[0.  0.5 1. ] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
"""
6.
np.eye() - creates identity matrix .... diagnoal is filled with 1 and remaining 0.

syntax:   np.eye(rows,columns,offest)

           rows - number of rows
           columns - number of columns
           offset - diagnol offset. It tells which diagnoal to be filled with 1. If it is 0 then the main diagnoal.
"""

array_1 = np.eye(3)
print(array_1,"\n")

array_2 = np.eye(2,3)
print(array_2,"\n")

array_3 = np.eye(3,5,2)
print(array_3,"\n")


#np.identity - It is also same as np.eye() but only craetes square martrix.

array_4 = np.identity(4)
print(array_4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[1. 0. 0.]
 [0. 1. 0.]] 

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
"""
7. np.linspace() - np.linspace() creates an array of evenly spaced numbers between a start and stop value — you specify how many values you want.only craetes one-dimensional array.

synatx:  linspace(start,stop,num=10)

          start - starting value(inclusive)
          stop - ending value(inclusive)
          num - specify the length you want.
"""
array_1 = np.linspace(1,10,num=5)
print(array_1,"\n")

array_2 = np.linspace(1,10,num=20)
print(array_2,"\n")

array_3 = np.linspace(20,21,num=5)
print(array_3,"\n")

array_4 = np.linspace(1,10,num=6,endpoint=False)  #to exclude stop
print(array_4)

[ 1.    3.25  5.5   7.75 10.  ] 

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ] 

[20.   20.25 20.5  20.75 21.  ] 

[1.  2.5 4.  5.5 7.  8.5]


In [ ]:
#8. np.random.rand() - generates numbers between 0 (inclusive) and 1 (exclusive).  - (uniform distribution)

#1d : 5 is the length
array_1d = np.random.rand(5)
print(array_1d,"\n")

#2d : 2 rows 3 columns
array_2d = np.random.rand(2,3)
print(array_2d,"\n")

#3d : 2 blocks,2 rows and 3 columns
array_3d = np.random.rand(2,2,3)
print(array_3d)

[0.02057751 0.23403929 0.09014218 0.15096338 0.46072443] 

[[6.81883101e-01 3.79857603e-04 5.47792538e-02]
 [2.35901695e-01 3.65029064e-01 7.06350242e-01]] 

[[[0.99165283 0.78475506 0.3872652 ]
  [0.63672479 0.8213459  0.76429759]]

 [[0.24387832 0.99296432 0.33020668]
  [0.40194717 0.33825963 0.87736688]]]


In [ ]:
#9. np.random.randn() - It generates values near to 0 either postive or negative. (Gaussian distribution)

#1d : 5 is the length
array_1d = np.random.randn(5)
print(array_1d,"\n")

#2d : 2 rows 3 columns
array_2d = np.random.randn(2,3)
print(array_2d,"\n")

#3d : 2 blocks,2 rows and 3 columns
array_3d = np.random.randn(2,2,3)
print(array_3d)

[-1.99349655 -0.41201834 -0.43666793 -0.97015638 -2.67947691] 

[[ 1.30425548 -1.59405566 -0.90596073]
 [ 1.30684697 -0.77592817  0.55637143]] 

[[[-0.41939884  0.83671562  0.278631  ]
  [ 0.94570346  0.920174   -0.34873808]]

 [[ 0.73134166 -0.1373518  -0.21575124]
  [ 0.18908374  1.70625478  0.87049548]]]


In [ ]:
"""
10. np.random.randint()  - It generates values in specified range.

syntax:    randint(start,stop,size=5)

           start - starting value(inclusive)
           stop - ending value(exclusive)
           size - It is optional and determines the size of array

"""

array_1 = np.random.randint(5)   #  a single integer between 0 - 4
print(array_1,"\n")

array_2 = np.random.randint(10,size=5)
print (array_2,"\n")

array_3 = np.random.randint(41,62,size=10)
print(array_3,"\n")

array_4 = np.random.randint(1,100,size=(2,3))
print(array_4)

0 

[3 4 3 3 0] 

[45 59 53 59 49 53 49 48 50 61] 

[[30 44 42]
 [12 37 15]]


# Array Data Types

1.   Data Types in Numpy
2.   dtype parameter
3.   .dtype attribute
4.   Type conversion : astype() method



1. Data Types in Numpy

Numpy supports different data types. They are:

Integers: int8, int16, int32, int64

Unsigned Integers: uint8, uint16, etc.

Floats: float16, float32, float64

Complex Numbers: complex64, complex128

Boolean: bool_

Strings: str_, unicode_ (U)

Objects: object_

Datetime: datetime64

Timedelta: timedelta64

In [ ]:
#2. dtype parameter  - used to determine the type of the data to be stored in an array.

import numpy as np

array_1 = np.array([1,2,3,4],dtype="float32")
print(array_1,"\n")

array_2 = np.ones((2,3),dtype="str")
print(array_2)

[1. 2. 3. 4.] 

[['1' '1' '1']
 ['1' '1' '1']]


In [ ]:
#3.  .dtype attribute - used to check the type of data stored in an array.

array_1 = np.array([1,2,3,4])
print(array_1.dtype,"\n")

array_2 = np.ones((2,3))
print(array_2.dtype)

int64 

float64


In [ ]:
#4. Type conversion - We use astype() method to convert the type of a data in an array.

print("First Array\n")

array_1 = np.array([1.1,2.3,4.6])
print(array_1.dtype)
convert_array_1 = array_1.astype('int')
print(convert_array_1)
print(convert_array_1.dtype)


print("Second array\n")

array_2 = np.array([1,2,3,4])
print(array_2.dtype)
convert_array_2 = array_2.astype('str')
print(convert_array_2)
print(convert_array_2.dtype)

First Array

float64
[1 2 4]
int64
Second array

int64
['1' '2' '3' '4']
<U21


# Array Indexing and Slicing



1.   Basic slicing
2.   array Indexing
3.   Boolean Indexing
4.   Fancy Indexing
5.   combination of slicing and indexing


In [ ]:
"""
1. Baisc Slicing - we use slicing to get the specified range of elemets and subarrays.It is only applies for one-dimensioanl arrays.

Syntax:   array[start:stop:step]

          start - starting index (inclusive) - defalut 0
          stop - ending index (exclusive)
          step - steps to jump - default 1
"""
import numpy as np

array = np.array([10,20,30,40,50,60,70,80,90,100])
print(array,"\n")

#without start and step
print(array[:7],"\n")    # index 0 - 6

#without stop and step
print(array[3:],"\n")

#with start,stop and step
print(array[3:8:2],"\n")

#without start and stop
print(array[::3],"\n")

#without start, stop and jump
print(array[::],"\n")

#negative slicing              #start index > stop index
print(array[-1:-7:-1])


[ 10  20  30  40  50  60  70  80  90 100] 

[10 20 30 40 50 60 70] 

[ 40  50  60  70  80  90 100] 

[40 60 80] 

[ 10  40  70 100] 

[ 10  20  30  40  50  60  70  80  90 100] 

[100  90  80  70  60  50]


In [ ]:
"""
2. Array Indexing - Accessing specific elements by tehir positions.

    We use single integer for a 1D array
    we use comma seperated tuple for a 2D or more.
"""

#1d :  array[index]

print("one dimension:")
array_1d = np.array([1,2,3,4,5,6,7,8,9,10])
print("\n",array_1d,"\n")

print(array_1d[5],"\n")

print(array_1d[len(array_1d)-1],"\n")

print(array_1d[2*3])


#2d : array[row,col]

print("Two Dimension:")

array_2d = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print("\n",array_2d,"\n")

print(array_2d[1,2])



one dimension:

 [ 1  2  3  4  5  6  7  8  9 10] 

6 

10 

7
Two Dimension:

 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

6


In [ ]:
"""
3. Boolean Indexing - using condition get access of elements. It selects all the elements in the array which satisfies the condition.

syntax:   array[condition]
"""

array_1d =np.array([10,15,20,25,30,40,50,60,65,70,80,85,90,100])

print(array_1d[array_1d >40])    #elements greater than 40

print(array_1d[array_1d%2==0])  #even numbers

print(array_1d[array_1d%2!=0])  #odd numbers

[ 50  60  65  70  80  85  90 100]
[ 10  20  30  40  50  60  70  80  90 100]
[15 25 65 85]


In [ ]:
#4.Fancy Indexing - we directly we indices to access the multiple elements in the array

#1d:  array[index1,index2,etc]

array_1d = np.array([10,20,30,40,50,60,70,80,90,100])

print(array_1d[[3]])

print(array_1d[[5,9,2]])

#2d : array[[index,index,etc],[index,index,etc]]

array_2d = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]])

print(array_2d[[1,0,2],[3,2,0]])   #(1,3),(0,2),(2,0)


[40]
[ 60 100  30]
[8 3 9]


In [ ]:
#5. Combination of slicing and indexing
# array[rows,columns]

array = np.array([[10,20,30,40],
                  [50,60,70,80],
                  [90,100,110,120],
                  [130,140,150,160]])

print(array[:,2])

print(array[2:,2])

print(array[2:3,1:2])

[ 30  70 110 150]
[110 150]
[[100]]


# Array Shape and Reshaping

1. .shape
2. .ndim
3. .size
4. reshape()
5. flatten() vs ravel()
6. transpose() and .T
7. expand_dims(), squeeze()

In [ ]:
#1.  .shape - It is an attribute used to find the shape of an array and it returns a shape on tuple

import numpy as np

#1d : (5,)
array_1d = np.arange(1,6)
print(array_1d.shape)

#2d : (3,4)
array_2d = np.ones((3,4))
print(array_2d.shape)

#3d : (2,2,3)
array_3d = np.zeros((2,2,3))
print(array_3d.shape)

(5,)
(3, 4)
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
(2, 2, 3)


In [ ]:
#2. .ndim - To find the dimension of an array

#1d:
array_1d = np.array([1,2,3,4,5,])
print(array_1d.ndim)

#2d:
array_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(array_2d.ndim)

#3d:
array_3d = np.array([[[1,2,3,4],
                      [5,6,7,8]]])
print(array_3d.ndim)

1
2
3


In [ ]:
#3.  .size - It returns total number of elements in anarray irrespective of the dimensions.

#1d:
array_1d = np.arange(1,34)
print(array_1d.size)

#2d:
array_2d = np.ones((3,4))
print(array_2d.size)

#3d:
array_3d = np.zeros((3,4,5))
print(array_3d.size)

33
12
60


In [ ]:
#4. reshape() - It is used to reshape the array from one shape to another without changing the data in the array. The total number of elements must stay the same.

print("One dimension to two dimension\n")

a = np.array([1,2,3,4,5,6])
print(a)
print("dim : ",a.ndim)
print("shape : ",a.shape)

print("After Reshape:\n")

b = a.reshape((2,3))
print(b)
print("dim : ",b.ndim)
print("shape : ",b.shape)


print("\nTwo dimension to one dimension")
c = np.array([[1,2,3,4],[5,6,7,8]])
print(c)
print("dim : ",c.ndim)
print("shape : ",c.shape)

print("After Reshape:\n")
d = c.reshape(8)
print(d)
print("dim : ",d.ndim)
print("shape : ",d.shape)

print("\nTwo dimension to three dimension\n")
array_2d = np.ones((3,4),dtype="int")
print(array_2d,"\n")

reshape_array_2d = array_2d.reshape((2,2,3))
print(reshape_array_2d)


One dimension to two dimension

[1 2 3 4 5 6]
dim :  1
shape :  (6,)
After Reshape:

[[1 2 3]
 [4 5 6]]
dim :  2
shape :  (2, 3)

Two dimension to one dimension
[[1 2 3 4]
 [5 6 7 8]]
dim :  2
shape :  (2, 4)
After Reshape:

[1 2 3 4 5 6 7 8]
dim :  1
shape :  (8,)

Two dimension to three dimension

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] 

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [ ]:
#5.flatten() vs ravel()

"""
flatten()                                                                       ravel()

i.    faltten() converts different dimensions arrays to 1D array.               i.    ravel() converts different dimensions arrays to 1D array.
ii.   It returns a copy.                                                        ii.   It returns the view only not copy.
iii.  Changes in copied array doesn't affect original array.                    iii.  Changes reflect in original array.
"""

array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

flatten_array = array.flatten()
ravel_array = array.ravel()

flatten_array[0] = 10     #doesn't affect on original array
ravel_array[0] = 20       #affects on original array

print("Flatten Array:\n ",flatten_array)
print("\nRavel Araray:\n",ravel_array)
print("\nOriginal Array:\n",array)

Flatten Array:
  [10  2  3  4  5  6  7  8  9]

Ravel Araray:
 [20  2  3  4  5  6  7  8  9]

Original Array:
 [[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
#6.  .T and transpose()
"""
.T  - It is an attribute used to reverse the axis. It is mostly used to 2D arrays as well as other dimensions if we only want to reverse the axis.
transpose() - Transpose is a method same as .T but the difference we can make custom axis with the help of transpose() method.

     In transpose - layers or depth = 0
                    rows = 1
                    columns = 2
"""

print("Two Dimensional array\n")
array_2d = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

print("Using .T:\n",array_2d.T)
print("Using transpose():\n",array_2d.transpose())


print("\nThree Dimensional array\n")
array_3d = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]])
print("Using .T:\n",array_3d.T)
print("Using transpose():\n",array_3d.transpose())
print("usimg transpose() custom : \n",array_3d.transpose(1,2,0))




Two Dimensional array

Using .T:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Using transpose():
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

Three Dimensional array

Using .T:
 [[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]
Using transpose():
 [[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]
usimg transpose() custom : 
 [[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


# Mathematical Operations



1.Element-wise:

     A. addition
     B. subtarction
     C. multiplication
     D. Divison

2.Exponentials:

     A. np.exp()
     B. np.power()

3.Trignometry:

     A.np.sin()
     B.np.cos()
     etc,...
  
4.Rounding:

     A. np.round()
     B. np.floor()
     C. np.ceil()
     D.np.trunc()


In [ ]:
#1. Element-wise operations  - To do a elemet-wise operation. The shape and size of the arrays must be the same

#1d array:
import numpy as np

print("One-Dimensional Array:")

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

#addition
print(np.add(a,b))

#subtraction
print(np.subtract(a,b))

#multiply
print(np.multiply(a,b))

#divison
print(np.divide(a,b))


#2d:
print("Two Dimenisoanl Array:\n")

a2 = np.array([[1,2,3,4],
               [5,6,7,8]])
b2 = np.array([[9,10,11,12],
               [13,14,15,16]])

print(np.add(a2,b2))
print(np.subtract(a2,b2))
print(np.multiply(a2,b2))
print(np.divide(a2,b2))




One-Dimensional Array:
[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
Two Dimenisoanl Array:

[[10 12 14 16]
 [18 20 22 24]]
[[-8 -8 -8 -8]
 [-8 -8 -8 -8]]
[[  9  20  33  48]
 [ 65  84 105 128]]
[[0.11111111 0.2        0.27272727 0.33333333]
 [0.38461538 0.42857143 0.46666667 0.5       ]]


In [ ]:
#exponentials - we use these functions to calculate expoenntials and powers

"""
A. np.expe()

   synatx: np.exp(x)

            It takes single input x that is an array
            It calculates e power x .... where e ~ 2.71828

"""

#1d :
print("One Dimensional Array:")

array_1d = np.array([1,2,3,4])

print(np.exp(array_1d))

#2d :
print("\nTwo Dimensioanl Array:")

array_2d = np.array([[1,2,3,4],
                     [5,6,7,8]])
print(np.exp(array_2d))


"""
B. np.power()

   syntax: np.power(x,y)

       It takes two arguments and both are arrays.
       It computes x power y.
"""
#1d :
print("\none Dimensioanl Array:")

x = np.array([2,2,2,2])
y = np.array([2,3,4,5])

print(np.power(x,y))  #x power y
print(np.power(y,y))  #y power y



One Dimensional Array:
[ 2.71828183  7.3890561  20.08553692 54.59815003]

Two Dimensioanl Array:
[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03]]

one Dimensioanl Array:
[ 4  8 16 32]
[   4   27  256 3125]


In [ ]:
#4. Rounding - It is used to clean up decimal numbers and format data for display or to work on it.

x = np.array([1.23, 2.58, 3.5, -1.4, -2.6])

#np.round() - rounds to the nearest value

print("np.round():")

print(np.round(x))
print(np.round(x,1))  #round up to one deciamal ..we can change how many decimals we want

#np.floor() - It rounds down value

print("\nnp.round():")
print(np.round(x))

#np.ceil() - It rounds up value

print("\nnp.ceil():")
print(np.ceil(x))

#np.trunc() - It removes the decimals

print("\nnp.trunc()")
print(np.trunc(x))

np.round():
[ 1.  3.  4. -1. -3.]
[ 1.2  2.6  3.5 -1.4 -2.6]

np.round():
[ 1.  3.  4. -1. -3.]

np.ceil():
[ 2.  3.  4. -1. -2.]

np.trunc()
[ 1.  2.  3. -1. -2.]


# Aggregate and Statistical Functions

1. np.sum()

   Adds all the elements in the array.

2. np.mean()

   It returns the average or mean of all the data in the array.

3. np.median()

   It returns median or central value of the array.
  
4. np.std()

   Measures how much the values in your data vary from the average.

5. np.var()

   same as standard deivation but it's gives square of the std to calculate more easily with big values. std returns negative values. By squaring we get variance so we can easily calculate positive values.

6. np.min()

   It returns the minimum value from the array.

7. np.max()

   It returns the maximum value from tha array.

8. np.argmin()

   It returns the index value of minimum value in the array.

9. np.argmax()

   It returns the index value od maximum value in the array.

10. np.percentile()
   
   Tells you the value below which a certain percentage of data falls.

11. np.quantile

   same as the percentile instead of whole value we use decimals.


In [ ]:
import numpy as np

array = np.array([10,20,30,40,50,100])

#np.sum()
print("np.sum() : ",np.sum(array))

#np.mean()
print("np.mean() : ",np.mean(array))

#np.median()
print("np.median() : ",np.median(array))

#np.std()
print("np.std() : ",np.std(array))

#np.var()
print("np.var() : ",np.var(array))

#np.min()
print("np.min() : ",np.min(array))

#np.max()
print("np.max() : ",np.max(array))

#np.argmin()
print("np.argmin() : ",np.argmin(array))

#np.argmax()
print("np.argmax() : ",np.argmax(array))

#np.percentile()
print("np.percentile() : ",np.percentile(array,50))  #when comapring with 50

#np.quantile()
print("np.quantile() : ",np.quantile(array,0.5))    #0.5 = 50 same as percentile

np.sum() :  250
np.mean() :  41.666666666666664
np.median() :  35.0
np.std() :  29.1070819942883
np.var() :  847.2222222222222
np.min() :  10
np.max() :  100
np.argmin() :  0
np.argmax() :  5
np.percentile() :  35.0
np.quantile() :  35.0


In [ ]:
#we can also perform these same operations with 2D arrays and more but specifiying the "axis".

array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])

print(np.sum(array))       #It will give all the elements sum

print(np.sum(array,axis=0))  #axis=0 is vertical [1+5+9=15 2+6+10=18 ......]

print(np.sum(array,axis=1))  #axis=1 is horizonatal [1+2+3+4=10  5+6+7+8=26  ...]



#we can perform all the operations as the same way


78
[15 18 21 24]
[10 26 42]


# Broadcasting

Broadcasting is NumPy’s way to perform operations on arrays of different shapes — without manually repeating data.

It automatically “stretches” the smaller array along the missing dimensions to match the bigger array, so operations like addition, multiplication work smoothly.


In [ ]:
# 1D+2D

array_1d = np.array([1,2,3,4])
array_2d = np.array([[10,11,12,13],[14,15,16,17]])

print(np.add(array_1d,array_2d))  #In this the two arrays shape is not same but broadcasting makes the 1d array like [1,2,3,4],[1,2,3,4] to do operation.


#scalar + array

scalar = 10
array = np.array([1,2,3,4])

print(scalar+array)    #It converts scalar to [10,10,10,10] to match the 1D array.


[[11 13 15 17]
 [15 17 19 21]]
[11 12 13 14]


# Vectorization

Vectorization means doing operations on whole arrays at once instead of using a loop to do element-by-element calculations.


we can say np.sum(),np.mean(),etc are vectorization functions because they perform operation on whole array not elemet-wise.

In [ ]:
array = np.array([[1,2,3,],
         [4,5,6]])

print(array*2)       #we are calculating whole array at once without using loops

[[ 2  4  6]
 [ 8 10 12]]


# Matrix Operations

1. matrix multiplication : @ or np.dot()
2. Determinant : np.linalg.det()
3. Inverse : np.linalg.inv()
4. Eigen values/vectors : np.linalg.eig()
5. Solving Equations : np.linalg.solve()

In [ ]:
"""
1. Matrix Multiplication :

It is to multiply both matrices and produce result matrix.
The rule that the columns of first matrix must be equal to the seconnd matrix.
We use  @ and np.dot() to find the multiplication of two matrices in numpy.
"""

import numpy as np

matrix1 = np.array([[1,2,3],
                    [4,5,6]])
matrix2 = np.array([[1,2],
                    [3,4],
                    [5,6]])

print("Result Matrix:\n",matrix1 @ matrix2)   #using @
print("Result Matrix :\n",np.dot(matrix1,matrix2))  #using np.dot()

Result Matrix:
 [[22 28]
 [49 64]]
Result Matrix :
 [[22 28]
 [49 64]]


In [ ]:
"""
2. Determinant
The determinant is a special scalar value calculated from a square matrix. It tells you important things about the matrix.
we use np.linalg.det() to calculate det.
we can only apply for square matrices.
"""
matrix1 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
matrix2 = np.array([[1,2],
                    [3,4]])

print("Araray 1 :\n",np.linalg.det(matrix1))
print("Araray 2 :\n",np.linalg.det(matrix2))


Araray 1 :
 0.0
Araray 2 :
 -2.0000000000000004


In [ ]:
"""
3. Inverse
The inverse of a square matrix A is another matrix, denoted A⁻¹, such that when you multiply A by A⁻¹, you get the identity matrix:

A×A⁻¹ = I
The inverse “undoes” the transformation done by A. It exists only if A is square and has a non-zero determinant.
We use np.linalg.inv() to find the inverse of the matrix.

matrix1 = np.array([[1,2,3],
                   [4,5,6],     It will give error because det is 0 . so no inevrse exists
                   [7,8,9]])
"""
matrix2 = np.array([[1,2],
                    [3,4]])

print("Array 2:\n",np.linalg.inv(matrix2))

Array 2:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
"""
#4. Egien values and Eigen vectors
Eigenvalues: Scalars that show how much eigenvectors are stretched/shrunk by the matrix.

Eigenvectors: Directions that don’t change under the transformation (except scaling).
"""
matrix1 = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

eigen_values,eigen_vectors = np.linalg.eig(matrix1)

print("Eigen Values:",eigen_values)
print("Eigen Vectors : ",eigen_vectors)

Eigen Values: [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Eigen Vectors :  [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [ ]:
"""
5. solving Equations
A matrix itself is not an equation, but when you use a matrix A to represent the coefficients of a system of linear equations, and a vector b to represent the constants on the right side, then you get an equation of the form:

𝐴×𝑥=𝑏

Here, A is the matrix of coefficients.
x is the vector of unknown variables you want to find.
b is the result vector.
"""
A = np.array([[3, 1],
              [1, 2]])
b = np.array([9, 8])

x = np.linalg.solve(A, b)
print(x)


[2. 3.]


# Random Module
Random module is a python module which provides functions to generate random numbers and random operation functions.

In [ ]:
"""
1. np.random.rand() - It generates the random values between 0 and 1.
"""
array1 = np.random.rand(5)
print(array1)
array2 = np.random.rand(2,3)
print(array2)

[0.01431667 0.5766075  0.92859071 0.66182064 0.52240911]
[[0.11243034 0.17707128 0.50603866]
 [0.55038141 0.1635477  0.37240508]]


In [ ]:
"""
2. np.random.randn() - It generates the numbers near to 0 either positive or negative
"""
array1 = np.random.randn(5)
print(array1)

[ 0.88176237  1.19656173 -0.51747458  2.51821879 -1.01875154]


In [ ]:
"""
3. np.random.randint(start,stop,size) - It generates random numbers in a specified range.
"""
array = np.random.randint(10,100,(2,3))
print(array)

[[48 35 25]
 [44 32 27]]


In [ ]:
"""
4.np.rando.seed() -  np.random.seed() when you want predictable, repeatable random results.
"""
np.random.seed(42)
array = np.random.randint(10,20,10)
print(array)


[16 13 17 14 16 19 12 16 17 14]


In [ ]:
"""
5. np.random.shuffle()  - we use it shuffle the elements in an array.
"""
array1 = np.array([1,2,3,4,5])
np.random.shuffle(array1)
print("array1 shuffled:\n",array1)

array2 = np.array([[1,2,3],
                   [4,5,6],   #It only shuffles rows for 2D and more dimensional matrices.
                   [7,8,9]])
np.random.shuffle(array2)
print("array2 shuffled:\n",array2)

array1 shuffled:
 [5 3 1 4 2]
array2 shuffled:
 [[1 2 3]
 [7 8 9]
 [4 5 6]]


In [ ]:
"""
6. np.random.choice() - it choose form a list of elements or a range.
"""

array = np.array([1,2,3,4,5])
choice1 = np.random.choice(array,5)
print(choice1)

#sampling without replacement - It choose everytime a unique element.
array2 = np.array([10,20,30,40,50])
choice2 = np.random.choice(array2,4,replace=False)
print(choice2)

[5 3 5 1 2]
[50 30 20 10]


# Set Opeartions

There are several set operations in the numpy . They only work on 1D arrays. If we want to perform on 2D and more we need advance tricks.Outputs are sorted by default.

1. np.unique()  - returns all the unique elemnts of an array
2. np.intersect1d() - returns all the common elemnts in two arrays.
3. np.union1d() - returns all the unique elements from both arrays.
4. np.setdiff1d() - returns Difference of arrays like a-b or b-a  Difference.
5. np.setxor1d() - returns all the elements which are not common in both arrays.

In [ ]:
a = np.array([1,2,3,5])
b = np.array([3,4,5,6])

print("Union : ",np.unique(a))
print("Intersection :",np.intersect1d(a,b))
print("Union :",np.union1d(a,b))
print("Difference a-b :",np.setdiff1d(a,b))
print("Difference b-a",np.setdiff1d(b,a))
print("XOR elements :",np.setxor1d(a,b))

Union :  [1 2 3 5]
Intersection : [3 5]
Union : [1 2 3 4 5 6]
Difference a-b : [1 2]
Difference b-a [4 6]
XOR elements : [1 2 4 6]


# Joining Arrays
We can join arrays with the help of following functions:

1. np.concatenate()
2. np.vstack()
3. np.hstack()


In [ ]:
"""
1. np.concatenate() - It is used to join two arrays.

Axis	              You are joining...     	      What must match

0	                     Adding rows	                  Columns
1	                    Adding columns	                  Rows

If we want to add rows the columns size must match that is axis=0.
If we want to add columns the rows size must match that is axis=1.
"""


#Adding rows
import numpy as np

a = np.array([[1,2],
              [3,4],
              [5,6]])

b = np.array([[10,20],
              [40,50]])

print(np.concatenate((a,b),axis=0))


#adding columns

c = np.array([[1,2,3,4],
              [5,6,7,8]])

d = np.array([[10,20],
              [30,40]])
print(np.concatenate((c,d),axis=1))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [10 20]
 [40 50]]
[[ 1  2  3  4 10 20]
 [ 5  6  7  8 30 40]]


In [ ]:
"""
2.vstack() - It is a vertical stack this is default of axis=0 in concatenation. Here it stack the array one below another.
              But it requires same number of columns.
"""

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([[1,2,3],
              [4,5,6]])
d = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(np.vstack((a,b)))
print(np.vstack((c,d)))
#print(np.vstack((a,c)))   It will raise error because columns doesn't match to stack.
#print(np.vstack((b,d)))   It will raise error because columns doesn't match to stack.

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
"""
3. np.hstack() -It is a Horozontal stack this is default of axis=1 in concatenation. Here it stack the array one after another horizonatlly.
              But it requires same number of rows.
"""
a = np.array([1,2,3,4])
b = np.array([5,6,7])

c = np.array([[1,2,3],
              [5,6,7]])
d = np.array([[2,3,4,5,6],
              [7,8,9,10,11]])

print(np.hstack((a,b)))
print(np.hstack((c,d)))
#print(np.hstack((a,c)))  It will raise error because rows not matched.

[1 2 3 4 5 6 7]
[[ 1  2  3  2  3  4  5  6]
 [ 5  6  7  7  8  9 10 11]]


# Splitting Arrays   
We can split arrays with the help of split functions. They are:

1. np.split()
2. np.array_split()
3. np.vsplit()
4. np.hsplit()

In [ ]:
"""
1. np.split()  - It is used to split arrays into different sub arrays.

syntax:   np.split(array, parts_or_indices, axis)

          array - We have to give compatable array as the first argument
          parts_or_indices - parts are no of arrays to form and indices use when we want to split arrays using indices
          axis - we can split arrays vertically or horzonatlly . Default axis=0 (vertical)
"""

#1d :
print("One dimensional:")
array = np.array([1,2,3,4,5,6,7,8,9,10])

print(np.split(array,5))   #It splits the array to 5 sub-arrays
#print(np.split(array,6))   It will raise error because array is not compatabile for 6 sub-arrays.

print(np.split(array,[2,6]))   # It splits array at 2nd and 6th index



#2d:
print("Two dimensional:")

array2 = np.array([[1,2,3,4,5],
                   [6,7,8,9,10],
                   [11,12,13,14,15]])

print(np.split(array2,5,axis=1))  #here axis=0 don't work because 5 sub arrays with 3 rows is not possible.
print(np.split(array2,3))





One dimensional:
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]
[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10])]
Two dimensional:
[array([[ 1],
       [ 6],
       [11]]), array([[ 2],
       [ 7],
       [12]]), array([[ 3],
       [ 8],
       [13]]), array([[ 4],
       [ 9],
       [14]]), array([[ 5],
       [10],
       [15]])]
[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15]])]


In [ ]:
"""
2. np.array_split() - unlike np.split() it allows uneven splits without any errors.
"""
array = np.array([1,2,3,4,5,5,6,7,8,9,10])

print(np.array_split(array,5))  #It is common because it divides 5 sub-arrays with 2 elements each

print(np.array_split(array,6))  #It is also possible with this function.


array_2d = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

print(np.array_split(array_2d,2))   #It is also possible

[array([1, 2, 3]), array([4, 5]), array([5, 6]), array([7, 8]), array([ 9, 10])]
[array([1, 2]), array([3, 4]), array([5, 5]), array([6, 7]), array([8, 9]), array([10])]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]])]


In [ ]:
"""
3. np.vsplit() - It is to split array into sub-arrays vertically. The rows must be compatable.
"""

array = np.array([[1,2,3,4],
                 [4,5,6,4],
                 [7,8,9,4]])

print(np.vsplit(array,3))  #but here(array,4) is not possible because it is uneven to split vertically.


[array([[1, 2, 3, 4]]), array([[4, 5, 6, 4]]), array([[7, 8, 9, 4]])]


In [ ]:
"""
4. np.hsplit() - It is to split array into sub-arrays horizontally. The columns must be compatable.
"""

array = np.array([[1,2,3,4],
                 [4,5,6,4],
                 [7,8,9,4]])

print(np.hsplit(array,4))    # but here (array,3) is not possible because it is uneven to split horizontally.

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]]), array([[4],
       [4],
       [4]])]


# Shallow Copy Vs Deep Copy
                                                                

In [ ]:
"""
Shallow copy                                                                    Deep Copy

1. It doesn't creayes new array.                                                1. It creates new array.
2. we can use assignembt operator to shallow copy (a = b).                      2. We use copy() function for deep copy (b = a.copy()).
3. Here 'a' and 'b' has same memory.                                            3. Here 'a' and 'b' has different memory.
4. Changes in 'b' will change 'a' also.                                         4. changes in 'b' doesn't affect 'a'.

"""
#shallow copy
a = np.array([1,2,3,4,5])
b = a
b[1] = 10    #It changes in 'a' also because they share same memory
print(b)
print(a)


#deep copy
deep_a = np.array([1,2,3,4,5])
deep_b = a.copy()
deep_b[1] = 10
print(deep_a) #It doesn't change because they share different memory
print(deep_b)

[ 1 10  3  4  5]
[ 1 10  3  4  5]
[1 2 3 4 5]
[ 1 10  3  4  5]


# Handling Missing Values

A missing value is just a blank or unknown value in your data.We can handle missing data in the arrays using numpy.



In [6]:
# 1. np.nan - nan is a "not a number". It is a special floating-point used to represent missing, undefined, not-valid valuesa

import numpy as np
data =  np.array([[1,2,np.nan],
                  [4,np.nan,6],
                  [np.nan,8,9]])
print(data)
print(np.sum(data))  #It will give "nan" as output this is the problem.

#we can do aggreagte functions with nan.
print(np.nansum(data))
print(np.nanmean(data))
#etc

print(type(np.nan))  #It's a float data type

[[ 1.  2. nan]
 [ 4. nan  6.]
 [nan  8.  9.]]
nan
30.0
5.0
<class 'float'>


In [7]:
#2. np.isnan() - It checks the "nan" is in the array or not. If it is it retuens true otherwise false.output is boolean array.
data =  np.array([[1,2,np.nan],
                  [4,np.nan,6],
                  [np.nan,8,9]])

mask = np.isnan(data)
print(mask)

[[False False  True]
 [False  True False]
 [ True False False]]


In [8]:
#3. np.inf and -np.inf - same as np.nan but these infinite values. np.inf = infinity and np.-inf = - infinity  .....like 1/0 and -1\0 etc will produce

data = np.array([[1,2,np.inf],
                 [np.nan,5,6],
                 [-np.inf,8,9]])
print(data)


[[  1.   2.  inf]
 [ nan   5.   6.]
 [-inf   8.   9.]]


In [9]:
#4.  np.nan_to_num() - we can replace nan to any nuber also inf values but optional.

data = np.array([[1,2,np.inf],
                 [np.nan,5,6],
                 [-np.inf,8,9]])

result_data = np.nan_to_num(data,nan=10,posinf=99,neginf=-99)

print(result_data)

[[  1.   2.  99.]
 [ 10.   5.   6.]
 [-99.   8.   9.]]


In [11]:
#5. Masking - maksing is selecting elements based on the condition. We use masking to ignore nan values. so,we can perform on good data.

#step-1 : Find the missing values
#step-2 : mask them with the help of np.isnan() function.
#step-3 : now get the valid data from the mask using operator ~
#step-4 : perform opertions on valid data.

data = np.array([[1,2,3],
                 [np.nan,5,np.nan],
                 [np.nan,8,9]])

mask = np.isnan(data)

valid_data = data[~mask]

print(valid_data)

[1. 2. 3. 5. 8. 9.]


# Memory layout



*   memory layout means how numpy arranges the multi-dimensional arrays in the memory.
*   Numpy arranges the multi-dimensionals in the form of 1D array in memory.
*   There are two types:
     

1.   'C' layout - It's a C-style order It considers rows as major.rows are stored together.
2.   'F' layout - It's a Fortran-style order It considers columns as major. Columns are stored together.


In [12]:
#Example for 'C' and 'F' style

array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

#C - style
print("C style:\n",array.ravel(order='c'))

#F - style
print("F Style:\n",array.ravel(order='F'))

C style:
 [1 2 3 4 5 6 7 8 9]
F Style:
 [1 4 7 2 5 8 3 6 9]
